channels_chat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from channels_chat import settings
from django.conf import settings

urlpatterns = [
    url(r'^', include('chat.urls', namespace='chat')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url('', include('social_django.urls', namespace='social')),# <--
    url("^soc/", include("social_django.urls", namespace="social")),
    url('', include('django.contrib.auth.urls', namespace='auth')),    
 url(r'social/',
        include('social.apps.django_app.urls', namespace='social')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from chat.views import home, get_messages, upload_photo, RoomEditView, GroupRoomEditView, get_group_messages, GroupChatCreateView, remove_group_chat, report_message, invite_friends, reports_mangement


urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^(?P<roomID>\d+)/$', home, name="home_with_id"),
    url(r'^group/(?P<group_roomID>\d+)/$', home, name="group_with_id"),
    url(r'^get_messages/(?P<room>.+)/$', get_messages, name="get_messages"),
    url(r'^get_group_messages/(?P<group>.+)/$', get_group_messages, name="get_group_messages"),
    url(r'^upload_photo/$', upload_photo, name="upload_photo"),
    url(r'^room-edit/(?P<room>.+)/$', RoomEditView.as_view(), name="edit_room"),
    url(r'^edit-group-room/(?P<room>.+)/$', GroupRoomEditView.as_view(), name="edit_group_room"),
    url(r'^create-group-chat/', GroupChatCreateView.as_view(), name="create_group_chat"),
    url(r'^remove-group-chat/(?P<room>.+)/$', remove_group_chat, name="remove_group_chat"),
    url(r'^invite_friends/$', invite_friends, name="invite_friends"),
    url(r'^report_message/(?P<type>.+)/(?P<id>.+)/$', report_message, name="report_message"),
    url(r'^reports-management/$', reports_mangement, name="reports_management"),
]

users/urls.py
from django.conf.urls import url
from users.views import RegisterView, home, view_profile, EditProfileView, ChangePasswordView, change_friends, LoginView, change_friend_request, delete_current_account, user_management, delete_account, block_account
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^login$', LoginView.as_view(), name="login"),
    url(r'^logout/$', logout, {'next_page': 'chat:home'}, name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^view/$', view_profile, name="view_profile"),
    url(r'^edit/$', EditProfileView.as_view(), name="edit_profile"),
    url(r'^change-password/$', ChangePasswordView.as_view(), name="change_password"),
    url(r'^connect/(?P<action>.+)/(?P<pk>\d+)$', change_friends, name="change_friends"),
    url(r'^change_friend_request/(?P<action>.+)/(?P<pk>\d+)$', change_friend_request, name="change_friend_request"),
    url(r'^delete/$', delete_current_account, name="delete_current_account"),
    url(r'^user-management/$', user_management, name="user_management"),
    url(r'^delete_account/(?P<userID>\d+)$', delete_account, name="delete_account"),
    url(r'^block_account/(?P<userID>\d+)$', block_account, name="block_account"),
    url(r'^reset-password/$', password_reset, {'template_name': 'users/reset_password.html', 'post_reset_redirect': 'users:password_reset_done', 'email_template_name':'users/reset_password_email.html', 'from_email': 'infochatroom13@gmail.com'}, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, {'template_name':'users/reset_password_done.html'}, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'users/reset_password_confirm.html', 'post_reset_redirect': 'users:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, {'template_name': 'users/reset_password_complete.html'}, name='password_reset_complete'),
]

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    block_expire = models.DateTimeField(default=datetime.datetime.now, blank=True)
    profile_photo = models.ImageField(upload_to='profile_photos', default='profile_photos/profile_image_default.png')

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Friend(models.Model):
    users = models.ManyToManyField(User, blank=True)
    current_user = models.ForeignKey(User, related_name='owner')

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )   
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )   
        friend.users.remove(new_friend)

class Friend_request(models.Model):

    requests_sent = models.ManyToManyField(User, related_name="requests_sent", blank=True)
    requests_received = models.ManyToManyField(User, related_name="requests_received", blank=True)
    current_user = models.ForeignKey(User, related_name='requests_owner')

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm
from users.models import Profile


class RegistrationForm(UserCreationForm):

    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:

        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):

        user = super(RegistrationForm, self).save(commit=True)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
            
        return user

    def __init__(self, *args, **kwargs):

        # first call the 'real' __init__()
        super(RegistrationForm, self).__init__(*args, **kwargs)
        # then do extra stuff:
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['class'] = 'form-control'
        

class EditUserForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'password'
        )
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),      
        }

class EditProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('profile_photo',)

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):

        # first call the 'real' __init__()
        super(AuthenticationForm, self).__init__(None, *args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        # then do extra stuff:

class ChangePassswordForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):

        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        
        self.fields['old_password'].widget.attrs['class'] = 'form-control'
        self.fields['new_password1'].widget.attrs['class'] = 'form-control'
        self.fields['new_password2'].widget.attrs['class'] = 'form-control'

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse, render_to_response
from django.views.generic import TemplateView
from users.forms import RegistrationForm, EditProfileForm, EditUserForm, LoginForm, ChangePassswordForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, login, authenticate
from django.contrib.auth.models import User
from models import Friend, Friend_request
from chat.models import Chat_room
from django.db.models import Q
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
import datetime
from django.utils import timezone
from django.contrib.auth.decorators import login_required





# Create your views here.


class RegisterView(TemplateView):

    def get(self, request):
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'users/register.html', args)

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect('/')
        else:
            return render(request, 'users/register.html', {'form': form})


class EditProfileView(TemplateView):
    
    def get(self, request):
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.profile)
        args = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, 'users/edit_profile.html', args)

    def post(self, request):
        user_form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST, request.FILES, instance=request.user.profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('users:view_profile')
        return HttpResponse("Something went wrong")

class ChangePasswordView(TemplateView):
    def get(self, request):
        form = ChangePassswordForm(user=request.user)
        args = {'form': form}
        return render(request, 'users/change-password.html', args)
    def post(self, request):
        form = PasswordChangeForm(data=request.POST, user=request.user);
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('users:view_profile')
        else:
            return redirect('users:change_password')

def view_profile(request):
    user = request.user
    args = {'user': user}
    return render(request, 'users/profile.html', args)

@login_required
def home(request):
    return render(request, 'users/home.html', {})

def change_friends(request, action, pk):
    if not request.user.is_authenticated():
        return redirect('chat:home')
    elif int(pk) == int(request.user.pk):
        return redirect('chat:home')
    else:
        new_user = User.objects.get(pk=pk)
        if action == 'add':
            
            if Chat_room.objects.filter((Q(user1=request.user) & Q(user2=new_user)) | (Q(user2=request.user) & Q(user1=new_user)) ).exists():
                pass
            else:
                room = Chat_room(user1=request.user, user2=new_user)
                room.save()
            
            Friend.make_friend(request.user, new_user)
            Friend.make_friend(new_user, request.user)

            requestUserObj = Friend_request.objects.get(current_user=request.user)
            userRequestedFriendshipObj = Friend_request.objects.get(current_user=User.objects.get(pk=pk))
            
            requestUserObj.requests_received.remove(User.objects.get(pk=pk))
            userRequestedFriendshipObj.requests_sent.remove(request.user)
            
        elif action == 'loose':
            Friend.lose_friend(request.user, new_user)
            Friend.lose_friend(new_user, request.user)
        return redirect('chat:home')

def change_friend_request(request, action, pk):

    try:
        currentUserObj = Friend_request.objects.get(current_user=request.user)
    except:
        currentUserObj = Friend_request.objects.create(current_user=request.user)

    try:
        friendObj = Friend_request.objects.get(current_user=User.objects.get(pk=pk))
    except:
        friendObj = Friend_request.objects.create(current_user=User.objects.get(pk=pk))

    if action=="send":
        currentUserObj.requests_sent.add(User.objects.get(pk=pk))
        friendObj.requests_received.add(request.user)
    elif action=="cancel":
        currentUserObj.requests_sent.remove(User.objects.get(pk=pk))
        friendObj.requests_received.remove(request.user)

    return redirect('chat:home')


class LoginView(TemplateView):

    def get(self, request):
        form = LoginForm()
        args = {'form': form}
        return render(request, 'users/login.html', args)

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        form.fields['username'].widget.attrs['class'] = 'form-control'
        form.fields['password'].widget.attrs['class'] = 'form-control'
        if form.is_valid():

            user = User.objects.get(pk=form.get_user_id())
            if user.profile.block_expire > timezone.now():
                messages.warning(request, 'Your account is blocked until ' + str(user.profile.block_expire))
                return redirect('/')
            else:
                login(request, form.get_user())
                return redirect('/')
        else:
            return render(request, 'users/login.html', {'form': form})

def delete_current_account(request):
    currentUser = User.objects.get(pk=request.user.pk)
    currentUser.delete()
    messages.success(request, 'Your account has been deleted!')
    return redirect('users:login')

@staff_member_required
def user_management(request):
    users = User.objects.filter(is_staff=False)
    args = {'users': users, 'now': timezone.now()}
    return render(request, 'users/user_management.html', args)

@staff_member_required
def delete_account(request, userID):
    targetuser = User.objects.get(pk=userID)
    targetuser.delete()
    messages.success(request, 'The account has been deleted!')
    return redirect('users:user_management')

@staff_member_required
def block_account(request, userID):
    targetuser = User.objects.get(pk=userID)
    date = datetime.datetime.now()
    date += datetime.timedelta(minutes=1)
    targetuser.profile.block_expire = date
    targetuser.save()
    messages.success(request, 'The account has been blocked!')
    return redirect('users:user_management')

users/templates/base.html
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

<link href='http://fonts.googleapis.com/css?family=Inconsolata:400,700' rel='stylesheet' type='text/css'>  
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <script src="{% static 'js/jscolor.js' %}"></script>
</head>

<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'chat:home' %}">Chat</a>
            {% else %}
            <a class="navbar-brand" href="{% url 'users:login' %}">Chat</a>
            {% endif %}
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            {% if user.is_authenticated %}
            <ul class="nav navbar-nav">
                <li><a href="{% url 'chat:home' %}">Home</a></li>
                <li><a href="{% url 'users:view_profile' %}">Profile</a></li>
                <li><a href="{% url 'users:edit_profile' %}">Edit profile</a></li>
                <li><a href="{% url 'users:change_password' %}">Change password</a></li>
                <li><a href="{% url 'chat:invite_friends' %}">Invite a friend</a></li>
                <!-- ONLY FOR ADMIN reikes padaryt -->
                {% if user.is_staff %}
                <li><a href="{% url 'users:user_management' %}">User management</a></li>
                <li><a href="{% url 'chat:reports_management' %}">Reports management</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><span class="logged-as"> Logged in as <strong>{{ user.username }}</strong></span></li>
                <li>
                    <a class="btn-padding" href="{% url 'users:logout' %}">
                        <div class="btn btn-danger">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    Log out
                        </div>
                    </a>
                </li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav">
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="btn-padding" href="{% url 'users:register' %}">
                        <div class="btn btn-warning">
                            <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
                            Register
                        </div>
                    </a>
                </li>
                <li>
                    <a class="btn-padding" href="{% url 'users:login' %}">
                        <div class="btn btn-success">
                            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                            Log in
                        </div>
                    </a>
                </li>
            </ul>
            {% endif %}
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    
    {% block content %}
    {% endblock %}
</div>
</body>


</html>