channels_chat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from channels_chat import settings
from django.conf import settings

urlpatterns = [
    url(r'^', include('chat.urls', namespace='chat')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url('', include('social_django.urls', namespace='social')),# <--
    url("^soc/", include("social_django.urls", namespace="social")),
    url('', include('django.contrib.auth.urls', namespace='auth')),    
 url(r'social/',
        include('social.apps.django_app.urls', namespace='social')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from chat.views import home, get_messages, upload_photo, RoomEditView, GroupRoomEditView, get_group_messages, GroupChatCreateView, remove_group_chat, report_message, invite_friends, reports_mangement


urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^(?P<roomID>\d+)/$', home, name="home_with_id"),
    url(r'^group/(?P<group_roomID>\d+)/$', home, name="group_with_id"),
    url(r'^get_messages/(?P<room>.+)/$', get_messages, name="get_messages"),
    url(r'^get_group_messages/(?P<group>.+)/$', get_group_messages, name="get_group_messages"),
    url(r'^upload_photo/$', upload_photo, name="upload_photo"),
    url(r'^room-edit/(?P<room>.+)/$', RoomEditView.as_view(), name="edit_room"),
    url(r'^edit-group-room/(?P<room>.+)/$', GroupRoomEditView.as_view(), name="edit_group_room"),
    url(r'^create-group-chat/', GroupChatCreateView.as_view(), name="create_group_chat"),
    url(r'^remove-group-chat/(?P<room>.+)/$', remove_group_chat, name="remove_group_chat"),
    url(r'^invite_friends/$', invite_friends, name="invite_friends"),
    url(r'^report_message/(?P<type>.+)/(?P<id>.+)/$', report_message, name="report_message"),
    url(r'^reports-management/$', reports_mangement, name="reports_management"),
]

users/urls.py
from django.conf.urls import url
from users.views import RegisterView, home, view_profile, EditProfileView, ChangePasswordView, change_friends, LoginView, change_friend_request, delete_current_account, user_management, delete_account, block_account
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^login$', LoginView.as_view(), name="login"),
    url(r'^logout/$', logout, {'next_page': 'chat:home'}, name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^view/$', view_profile, name="view_profile"),
    url(r'^edit/$', EditProfileView.as_view(), name="edit_profile"),
    url(r'^change-password/$', ChangePasswordView.as_view(), name="change_password"),
    url(r'^connect/(?P<action>.+)/(?P<pk>\d+)$', change_friends, name="change_friends"),
    url(r'^change_friend_request/(?P<action>.+)/(?P<pk>\d+)$', change_friend_request, name="change_friend_request"),
    url(r'^delete/$', delete_current_account, name="delete_current_account"),
    url(r'^user-management/$', user_management, name="user_management"),
    url(r'^delete_account/(?P<userID>\d+)$', delete_account, name="delete_account"),
    url(r'^block_account/(?P<userID>\d+)$', block_account, name="block_account"),
    url(r'^reset-password/$', password_reset, {'template_name': 'users/reset_password.html', 'post_reset_redirect': 'users:password_reset_done', 'email_template_name':'users/reset_password_email.html', 'from_email': 'infochatroom13@gmail.com'}, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, {'template_name':'users/reset_password_done.html'}, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'users/reset_password_confirm.html', 'post_reset_redirect': 'users:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, {'template_name': 'users/reset_password_complete.html'}, name='password_reset_complete'),
]

chat/forms.py
from django import forms
from chat.models import Chat_room, Chat_group
from django.forms import ModelForm
from users.models import User, Friend
from django.db.models import Q


class RoomEditForm(ModelForm):

    class Meta:

        model = Chat_room
        fields = (
            'title',
            'background_color',
        )
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'background_color': forms.TextInput(attrs={'class': 'form-control jscolor'}),      
        }

class GroupRoomEditForm(ModelForm):
    
    class Meta:

        model = Chat_group
        fields = (
            'title',
            'background_color',
            'users',
            'chat_admin'
        )
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'background_color': forms.TextInput(attrs={'class': 'form-control jscolor'}),
            'users': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
            'chat_admin': forms.HiddenInput()
        }
    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        
        super(GroupRoomEditForm, self).__init__(*args, **kwargs)

        friends = {}
        try:
            friend = Friend.objects.get(current_user=user)
            friends = friend.users.all()
        except:
            pass
        friend_ids = []

        for item in friends:
            friend_ids.append(item.pk)

        self.fields['users'].queryset = User.objects.filter(pk__in = friend_ids)

class EmailForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField()
    

chat/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User
from users.models import Friend, Friend_request
import json
from django.http import JsonResponse
from django.core import serializers
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from channels_chat import settings
import os
import time
from chat.models import Chat_room, ChatMessage, Chat_group, GroupChatMessage, MessageReport
from django.views.generic import TemplateView
from django.db.models import Q
from chat.forms import RoomEditForm, GroupRoomEditForm, EmailForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from chat.forms import RoomEditForm, GroupRoomEditForm
from django.contrib.admin.views.decorators import staff_member_required
# Create your views here.

@login_required
def home(request, roomID=None, group_roomID=None):

    friends = {}
    skip_user_ids = []
    requests_sent = {}
    requests_received = {}
    group_chats = []

    try:
        friend = Friend.objects.get(current_user=request.user)
        friends = friend.users.all()
    except:
        pass

    for friend in friends:
        room = Chat_room.objects.get( (Q(user1=request.user) & Q(user2=friend)) | (Q(user2=request.user) & Q(user1=friend)) )
        friend.room = room.pk
        skip_user_ids.append(friend.pk)

    skip_user_ids.append(request.user.pk)
 
    try:
        reqests_obj = Friend_request.objects.get(current_user=request.user)
        requests_sent = reqests_obj.requests_sent.all()
        requests_received = reqests_obj.requests_received.all()
    except:
        pass
    
    for user in requests_sent:
        skip_user_ids.append(user.pk)

    for user in requests_received:
        skip_user_ids.append(user.pk)

    try:
        group_chats_unfiltered = Chat_group.objects.filter(global_group=False)
    except:
        pass

    for group_chat in group_chats_unfiltered:
        group_chat.room = group_chat.pk
        group_chat_users = group_chat.users.all()
        for group_chat_user in group_chat_users:
            if group_chat_user == request.user:
                group_chats.append(group_chat)

    users = User.objects.filter(~Q(pk__in = skip_user_ids))

    if roomID:
        args = {'users': users, 'friends': friends, 'current_user_id': request.user.pk, 'roomID': roomID, 'group_roomID': "False", 'requests_received': requests_received, 'requests_sent': requests_sent, 'group_chats': group_chats}
    elif group_roomID:
        args = {'users': users, 'friends': friends, 'current_user_id': request.user.pk, 'roomID': "False", 'group_roomID': group_roomID, 'requests_received': requests_received, 'requests_sent': requests_sent, 'group_chats': group_chats}
    else:
        args = {'users': users, 'friends': friends, 'current_user_id': request.user.pk, 'roomID': "False", 'group_roomID': "False", 'requests_received': requests_received, 'requests_sent': requests_sent, 'group_chats': group_chats}


    return render(request, 'chat/home.html', args)

def get_messages(request, room):

    targetroom = Chat_room.objects.get(pk=room)

    query_data = ChatMessage.objects.filter(room=targetroom).order_by('-created')[:20]

    messages = []
    
    for item in query_data:
        messages.append({
            "created": item.created.strftime("%Y-%m-%d %H:%M"),
            "message": item.message,
            "room": item.room.pk,
            "username": item.user.username,
            "profile_photo": str(item.user.profile.profile_photo),
            "user_id": item.user.pk,
            "content_type": item.content_type,
            "message_pk": item.pk
        })

    return HttpResponse(json.dumps(messages))

def get_group_messages(request, group):

    messages = []

    if group == "global":
        try:
            targetgroup = Chat_group.objects.get(global_group=True)
        except:
            return HttpResponse(json.dumps(messages))
    else:
        targetgroup = Chat_group.objects.get(pk=group)

    query_data = GroupChatMessage.objects.filter(group=targetgroup).order_by('-created')[:20]

    for item in query_data:
        messages.append({
            "created": item.created.strftime("%Y-%m-%d %H:%M"),
            "message": item.message,
            "group": item.group.pk,
            "username": item.user.username,
            "profile_photo": str(item.user.profile.profile_photo),
            "user_id": item.user.pk,
            "content_type": item.content_type,
            "message_pk": item.pk
        })

    return HttpResponse(json.dumps(messages))

@csrf_exempt
def upload_photo(request):

    image = request.FILES['image']
    room = request.POST['room']
    timestamp = int(time.time())

    filename = str(timestamp) + ".jpg"

    if not os.path.exists(os.path.join(settings.MEDIA_ROOT, "room_images", room)):
        os.makedirs(os.path.join(settings.MEDIA_ROOT, "room_images", room))

    with open(os.path.join(settings.MEDIA_ROOT, "room_images", room, filename), 'w+') as destination:
        for chunk in image.chunks():
            destination.write(chunk)

    return HttpResponse(json.dumps({
        'imagename': os.path.join(room, filename),
        'room': room
    }))

class RoomEditView(TemplateView):
    def get(self, request, room):
        if room =='0':
            return redirect('chat:home')
        else:
            room = Chat_room.objects.get(pk=room)
            form = RoomEditForm(instance=room)   
            args = {"form": form}
            return render(request, 'chat/edit_room.html', args);
        
    def post(self,request, room):
        room = Chat_room.objects.get(pk=room)
        form = RoomEditForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('chat:home_with_id', roomID= str(room.pk))
        return redirect('chat:home')

class GroupChatCreateView(TemplateView):
    def get(self, request):
        
        form = GroupRoomEditForm(user=request.user, initial={'chat_admin': request.user})
        args = {"form": form}
        return render(request, 'chat/create_group_chat.html', args)
        
    def post(self,request):
        form = GroupRoomEditForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            the_last_chat = Chat_group.objects.last()
            the_last_chat.users.add(request.user)
            return redirect('chat:group_with_id', group_roomID=str(the_last_chat.pk))
        return redirect('chat:home')

class GroupRoomEditView(TemplateView):
    def get(self, request, room):
        if room =='0':
            return redirect('chat:home')
        else:
            room = Chat_group.objects.get(pk=room)
            form = GroupRoomEditForm(user=request.user, instance=room)
            friend = Friend.objects.get(current_user=request.user)
            friends = friend.users.all()
            args = {"form": form, 'friends': friends}
            return render(request, 'chat/edit_group_room.html', args);
        
    def post(self,request, room):
        room = Chat_group.objects.get(pk=room)
        form = GroupRoomEditForm(request.POST, user=request.user, instance=room)
        if form.is_valid():
            form.save()
            room.users.add(request.user)
            return redirect('chat:group_with_id', group_roomID= str(room.pk))
        return redirect('chat:home')
        
def remove_group_chat(self, room):
    currentRoom = Chat_group.objects.get(pk=room)
    currentRoom.delete()
    return redirect('chat:home')

def invite_friends(request):
    subject = request.user.username + ' is inviting you to join the Chat'
    message = 'Hello, your friend ' + request.user.username + ' sent you an invitation to join the most amazing platform "Chat". Register and enjoy all of the chats for free!'
    form = EmailForm(request.POST or None, initial={'subject': subject, 'message': message})
    args = {"form": form}
    if form.is_valid():
        subject = request.POST.get('subject', '')
        message = request.POST.get('message', '')
        email = request.POST.get('email', '')
        from_email = 'infochatroom13@gmail.com'
        if subject and message and from_email:
            try:
                send_mail(subject, message, from_email, [email])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.success(request, 'Message was sent!')
            return redirect('chat:invite_friends')
        else:
            # In reality we'd use a form class
            # to get proper validation errors.
            return HttpResponse('Make sure all fields are entered and valid.')
    return render(request, "chat/invite_friends.html", args)

def report_message(request, type, id):
    if type == 'private':
        message = ChatMessage.objects.get(pk=id)
    elif type == 'group':
        message = GroupChatMessage.objects.get(pk=id)

    if MessageReport.objects.filter(message=message.message, reported_user=message.user,reported_by=request.user):
        return HttpResponse(json.dumps({
            'status': 'This message is already reported'
        }))
    else:
        MessageReport.objects.create(message=message.message, reported_user=message.user,reported_by=request.user, content_type=message.content_type)
        return HttpResponse(json.dumps({
            'status': 'Message successfully reported'
        }))

@staff_member_required
def reports_mangement(request):
    reported_messages = MessageReport.objects.all()
    return render(request, 'chat/reports_management.html', {'reported_messages': reported_messages})

chat/templates/chat/create_group_chat.html
{% extends "base.html" %}

{% block content %}        
    <div class="container">
        <div class="col-lg-4">
            <div class="edit-room-form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <div class="button-panel">
                        <button type="submit" class="btn btn-default">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-8">
            <h1>Create a group chat</h1>
            <div class="panel-heading top-bar">
                    <div class="col-md-8 col-xs-8">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-comment"></span><span id="chat_title_id">Chat</span></h3>
                    </div>
                    <div class="col-md-4 col-xs-4" style="text-align: right;">
                        <a id="room_edit_link" href="{% url 'chat:edit_room' room=0 %}"><span class="glyphicon glyphicon-wrench edit-chat"></span></a>
                    </div>
            </div>
            <div id="chat_room">
                
            </div>
            <div class="panel-footer">
                    <div class="input-group">
                        <input id='chat_input' type="text" class="form-control input-sm chat_input" placeholder="Write your message here..." >
                        <span class="input-group-btn">
                            <label id="image-label" class="btn btn-default btn-file disabled">
                                <span class="glyphicon glyphicon-picture" aria-hidden="true"></span> 
                                <input type="file" name="image" id="chat_file_input" style="display: none;">
                            </label>
                            <button class="btn btn-primary btn-sm" id="btn-chat" disabled=true>Send</button>
                        </span>
                    </div>
                </div>
        </div>
    </div>
    <script>
        document.getElementById('chat_title_id').innerText = document.getElementById('id_title').value;
        document.getElementById('chat_room').style.background = "#" + document.getElementById('id_background_color').value;
        document.getElementById('id_title').addEventListener('change', function(){
            document.getElementById('chat_title_id').innerText = document.getElementById('id_title').value;
        });
        document.getElementById('id_background_color').addEventListener('change', function(){
            document.getElementById('chat_room').style.background = "#" + document.getElementById('id_background_color').value;
        });
	</script>


{% endblock content %}

chat/templates/chat/edit_group_room.html
{% extends "base.html" %}

{% block content %}        

    <div class="container">
        <div class="col-lg-4">
            <div class="edit-room-form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <div class="button-panel">
                        <button type="submit" class="btn btn-default">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-8">
            <h1>Edit group room</h1>
            <div class="panel-heading top-bar">
                    <div class="col-md-8 col-xs-8">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-comment"></span><span id="chat_title_id">Chat</span></h3>
                    </div>
                    <div class="col-md-4 col-xs-4" style="text-align: right;">
                        <a id="room_edit_link" href="{% url 'chat:edit_room' room=0 %}"><span class="glyphicon glyphicon-wrench edit-chat"></span></a>
                    </div>
            </div>
            <div id="chat_room">
                
            </div>
            <div class="panel-footer">
                    <div class="input-group">
                        <input id='chat_input' type="text" class="form-control input-sm chat_input" placeholder="Write your message here..." >
                        <span class="input-group-btn">
                            <label id="image-label" class="btn btn-default btn-file disabled">
                                <span class="glyphicon glyphicon-picture" aria-hidden="true"></span> 
                                <input type="file" name="image" id="chat_file_input" style="display: none;">
                            </label>
                            <button class="btn btn-primary btn-sm" id="btn-chat" disabled=true>Send</button>
                        </span>
                    </div>
                </div>
        </div>
    </div>
    <script>
        document.getElementById('chat_title_id').innerText = document.getElementById('id_title').value;
        document.getElementById('chat_room').style.background = "#" + document.getElementById('id_background_color').value;
        document.getElementById('id_title').addEventListener('change', function(){
            document.getElementById('chat_title_id').innerText = document.getElementById('id_title').value;
        });
        document.getElementById('id_background_color').addEventListener('change', function(){
            document.getElementById('chat_room').style.background = "#" + document.getElementById('id_background_color').value;
        });
	</script>


{% endblock content %}

chat/templates/chat/edit_room.html
{% extends "base.html" %}

{% block content %}        

    <div class="container">
        <div class="col-lg-4">
            <div class="edit-room-form">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>
                    <div class="button-panel">
                        <button type="submit" class="btn btn-default">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-8">
            <h1>Edit room</h1>
            <div class="panel-heading top-bar">
                    <div class="col-md-8 col-xs-8">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-comment"></span><span id="chat_title_id">Chat</span></h3>
                    </div>
                    <div class="col-md-4 col-xs-4" style="text-align: right;">
                        <a id="room_edit_link" href="{% url 'chat:edit_room' room=0 %}"><span class="glyphicon glyphicon-wrench edit-chat"></span></a>
                    </div>
            </div>
            <div id="chat_room">
                
            </div>
            <div class="panel-footer">
                    <div class="input-group">
                        <input id='chat_input' type="text" class="form-control input-sm chat_input" placeholder="Write your message here..." >
                        <span class="input-group-btn">
                            <label id="image-label" class="btn btn-default btn-file disabled">
                                <span class="glyphicon glyphicon-picture" aria-hidden="true"></span> 
                                <input type="file" name="image" id="chat_file_input" style="display: none;">
                            </label>
                            <button class="btn btn-primary btn-sm" id="btn-chat" disabled=true>Send</button>
                        </span>
                    </div>
                </div>
        </div>
    </div>
    <script>
        document.getElementById('chat_title_id').innerText = document.getElementById('id_title').value;
        document.getElementById('chat_room').style.background = "#" + document.getElementById('id_background_color').value;
        document.getElementById('id_title').addEventListener('change', function(){
            document.getElementById('chat_title_id').innerText = document.getElementById('id_title').value;
        });
        document.getElementById('id_background_color').addEventListener('change', function(){
            document.getElementById('chat_room').style.background = "#" + document.getElementById('id_background_color').value;
        });
	</script>


{% endblock content %}

chat/templates/chat/invite_friends.html
{% extends "base.html" %}

{% block content %}
    </br>
    </br>
    <div class="container">
        <form class="form-horizontal" role="form" method="post">
        {% csrf_token %}
            <div class="form-group">
                <label for="name" class="col-sm-2 control-label">Subject</label>
                <div class="col-sm-10">
                    {{ form.subject }}
                </div>
            </div>
            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    {{ form.email }}
                </div>
            </div>
            <div class="form-group">
                <label for="message" class="col-sm-2 control-label">Message</label>
                <div class="col-sm-10">
                    {{ form.message }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

chat/templates/chat/reports_management.html
{% extends "base.html" %}
{% block content %}

<hr>
<div class="container bootstrap snippet">

{% if reported_messages %}
    <div class="row">
        <div class="col-lg-12">
            <div class="main-box no-header clearfix">
                <div class="main-box-body clearfix">
                    <div class="table-responsive">
                        <table class="table user-list">
                            <thead>
                                <tr>
                                <th><span>Reported user</span></th>
                                <th><span>Message</span></th>
                                <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in reported_messages %}
                                <tr>
                                    <td>
                                        <img src="/media/{{ item.reported_user.profile.profile_photo }}" alt="">
                                        <a href="#" class="user-link">{{item.reported_user}}</a>
                                        <span class="user-subhead">ID: {{item.reported_user.pk}}</span>
                                    </td>
                                    <td class="text-left">
                                        {% if item.content_type == 'text' %}
                                            <p> {{ item.message }}</p>
                                        {% else %}
                                            <img src="/media/room_images/{{ item.message }}" >
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a href="#">{{item.reported_user.email}}</a>
                                    </td>
                                    <td style="width: 20%;">
                                        <a href="{% url 'users:block_account' userID=item.reported_user.pk %}" class="table-link warning" onclick="return confirm('Are you sure you want to block this account?');">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-minus-circle fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                        <a href="{% url 'users:delete_account' userID=item.reported_user.pk %}" class="table-link danger" onclick="return confirm('Are you sure you want to delete this account?');">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %} 
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %} 
    <div class="alert alert-danger">
        <strong>There are no reported messages in the database</strong>
    </div> 
    {% endif %}  
</div>
{% endblock content %}