channels_chat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from channels_chat import settings
from django.conf import settings

urlpatterns = [
    url(r'^', include('chat.urls', namespace='chat')),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^chat/', include('chat.urls', namespace='chat')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url('', include('social_django.urls', namespace='social')),# <--
    url("^soc/", include("social_django.urls", namespace="social")),
    url('', include('django.contrib.auth.urls', namespace='auth')),    
 url(r'social/',
        include('social.apps.django_app.urls', namespace='social')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url
from chat.views import home, get_messages, upload_photo, RoomEditView, GroupRoomEditView, get_group_messages, GroupChatCreateView, remove_group_chat, report_message, invite_friends, reports_mangement


urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^(?P<roomID>\d+)/$', home, name="home_with_id"),
    url(r'^group/(?P<group_roomID>\d+)/$', home, name="group_with_id"),
    url(r'^get_messages/(?P<room>.+)/$', get_messages, name="get_messages"),
    url(r'^get_group_messages/(?P<group>.+)/$', get_group_messages, name="get_group_messages"),
    url(r'^upload_photo/$', upload_photo, name="upload_photo"),
    url(r'^room-edit/(?P<room>.+)/$', RoomEditView.as_view(), name="edit_room"),
    url(r'^edit-group-room/(?P<room>.+)/$', GroupRoomEditView.as_view(), name="edit_group_room"),
    url(r'^create-group-chat/', GroupChatCreateView.as_view(), name="create_group_chat"),
    url(r'^remove-group-chat/(?P<room>.+)/$', remove_group_chat, name="remove_group_chat"),
    url(r'^invite_friends/$', invite_friends, name="invite_friends"),
    url(r'^report_message/(?P<type>.+)/(?P<id>.+)/$', report_message, name="report_message"),
    url(r'^reports-management/$', reports_mangement, name="reports_management"),
]

users/urls.py
from django.conf.urls import url
from users.views import RegisterView, home, view_profile, EditProfileView, ChangePasswordView, change_friends, LoginView, change_friend_request, delete_current_account, user_management, delete_account, block_account
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^login$', LoginView.as_view(), name="login"),
    url(r'^logout/$', logout, {'next_page': 'chat:home'}, name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^view/$', view_profile, name="view_profile"),
    url(r'^edit/$', EditProfileView.as_view(), name="edit_profile"),
    url(r'^change-password/$', ChangePasswordView.as_view(), name="change_password"),
    url(r'^connect/(?P<action>.+)/(?P<pk>\d+)$', change_friends, name="change_friends"),
    url(r'^change_friend_request/(?P<action>.+)/(?P<pk>\d+)$', change_friend_request, name="change_friend_request"),
    url(r'^delete/$', delete_current_account, name="delete_current_account"),
    url(r'^user-management/$', user_management, name="user_management"),
    url(r'^delete_account/(?P<userID>\d+)$', delete_account, name="delete_account"),
    url(r'^block_account/(?P<userID>\d+)$', block_account, name="block_account"),
    url(r'^reset-password/$', password_reset, {'template_name': 'users/reset_password.html', 'post_reset_redirect': 'users:password_reset_done', 'email_template_name':'users/reset_password_email.html', 'from_email': 'infochatroom13@gmail.com'}, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, {'template_name':'users/reset_password_done.html'}, name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'users/reset_password_confirm.html', 'post_reset_redirect': 'users:password_reset_complete'}, name='password_reset_confirm'),
    url(r'^reset-password/complete/$', password_reset_complete, {'template_name': 'users/reset_password_complete.html'}, name='password_reset_complete'),
]

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    block_expire = models.DateTimeField(default=datetime.datetime.now, blank=True)
    profile_photo = models.ImageField(upload_to='profile_photos', default='profile_photos/profile_image_default.png')

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

class Friend(models.Model):
    users = models.ManyToManyField(User, blank=True)
    current_user = models.ForeignKey(User, related_name='owner')

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )   
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )   
        friend.users.remove(new_friend)

class Friend_request(models.Model):

    requests_sent = models.ManyToManyField(User, related_name="requests_sent", blank=True)
    requests_received = models.ManyToManyField(User, related_name="requests_received", blank=True)
    current_user = models.ForeignKey(User, related_name='requests_owner')

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, PasswordChangeForm
from users.models import Profile


class RegistrationForm(UserCreationForm):

    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:

        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):

        user = super(RegistrationForm, self).save(commit=True)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
            
        return user

    def __init__(self, *args, **kwargs):

        # first call the 'real' __init__()
        super(RegistrationForm, self).__init__(*args, **kwargs)
        # then do extra stuff:
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['class'] = 'form-control'
        

class EditUserForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'password'
        )
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),      
        }

class EditProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('profile_photo',)

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):

        # first call the 'real' __init__()
        super(AuthenticationForm, self).__init__(None, *args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        # then do extra stuff:

class ChangePassswordForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):

        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        
        self.fields['old_password'].widget.attrs['class'] = 'form-control'
        self.fields['new_password1'].widget.attrs['class'] = 'form-control'
        self.fields['new_password2'].widget.attrs['class'] = 'form-control'

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse, render_to_response
from django.views.generic import TemplateView
from users.forms import RegistrationForm, EditProfileForm, EditUserForm, LoginForm, ChangePassswordForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, login, authenticate
from django.contrib.auth.models import User
from models import Friend, Friend_request
from chat.models import Chat_room
from django.db.models import Q
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
import datetime
from django.utils import timezone
from django.contrib.auth.decorators import login_required





# Create your views here.


class RegisterView(TemplateView):

    def get(self, request):
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'users/register.html', args)

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect('/')
        else:
            return render(request, 'users/register.html', {'form': form})


class EditProfileView(TemplateView):
    
    def get(self, request):
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.profile)
        args = {'user_form': user_form, 'profile_form': profile_form}
        return render(request, 'users/edit_profile.html', args)

    def post(self, request):
        user_form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST, request.FILES, instance=request.user.profile)
        
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('users:view_profile')
        return HttpResponse("Something went wrong")

class ChangePasswordView(TemplateView):
    def get(self, request):
        form = ChangePassswordForm(user=request.user)
        args = {'form': form}
        return render(request, 'users/change-password.html', args)
    def post(self, request):
        form = PasswordChangeForm(data=request.POST, user=request.user);
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('users:view_profile')
        else:
            return redirect('users:change_password')

def view_profile(request):
    user = request.user
    args = {'user': user}
    return render(request, 'users/profile.html', args)

@login_required
def home(request):
    return render(request, 'users/home.html', {})

def change_friends(request, action, pk):
    if not request.user.is_authenticated():
        return redirect('chat:home')
    elif int(pk) == int(request.user.pk):
        return redirect('chat:home')
    else:
        new_user = User.objects.get(pk=pk)
        if action == 'add':
            
            if Chat_room.objects.filter((Q(user1=request.user) & Q(user2=new_user)) | (Q(user2=request.user) & Q(user1=new_user)) ).exists():
                pass
            else:
                room = Chat_room(user1=request.user, user2=new_user)
                room.save()
            
            Friend.make_friend(request.user, new_user)
            Friend.make_friend(new_user, request.user)

            requestUserObj = Friend_request.objects.get(current_user=request.user)
            userRequestedFriendshipObj = Friend_request.objects.get(current_user=User.objects.get(pk=pk))
            
            requestUserObj.requests_received.remove(User.objects.get(pk=pk))
            userRequestedFriendshipObj.requests_sent.remove(request.user)
            
        elif action == 'loose':
            Friend.lose_friend(request.user, new_user)
            Friend.lose_friend(new_user, request.user)
        return redirect('chat:home')

def change_friend_request(request, action, pk):

    try:
        currentUserObj = Friend_request.objects.get(current_user=request.user)
    except:
        currentUserObj = Friend_request.objects.create(current_user=request.user)

    try:
        friendObj = Friend_request.objects.get(current_user=User.objects.get(pk=pk))
    except:
        friendObj = Friend_request.objects.create(current_user=User.objects.get(pk=pk))

    if action=="send":
        currentUserObj.requests_sent.add(User.objects.get(pk=pk))
        friendObj.requests_received.add(request.user)
    elif action=="cancel":
        currentUserObj.requests_sent.remove(User.objects.get(pk=pk))
        friendObj.requests_received.remove(request.user)

    return redirect('chat:home')


class LoginView(TemplateView):

    def get(self, request):
        form = LoginForm()
        args = {'form': form}
        return render(request, 'users/login.html', args)

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        form.fields['username'].widget.attrs['class'] = 'form-control'
        form.fields['password'].widget.attrs['class'] = 'form-control'
        if form.is_valid():

            user = User.objects.get(pk=form.get_user_id())
            if user.profile.block_expire > timezone.now():
                messages.warning(request, 'Your account is blocked until ' + str(user.profile.block_expire))
                return redirect('/')
            else:
                login(request, form.get_user())
                return redirect('/')
        else:
            return render(request, 'users/login.html', {'form': form})

def delete_current_account(request):
    currentUser = User.objects.get(pk=request.user.pk)
    currentUser.delete()
    messages.success(request, 'Your account has been deleted!')
    return redirect('users:login')

@staff_member_required
def user_management(request):
    users = User.objects.filter(is_staff=False)
    args = {'users': users, 'now': timezone.now()}
    return render(request, 'users/user_management.html', args)

@staff_member_required
def delete_account(request, userID):
    targetuser = User.objects.get(pk=userID)
    targetuser.delete()
    messages.success(request, 'The account has been deleted!')
    return redirect('users:user_management')

@staff_member_required
def block_account(request, userID):
    targetuser = User.objects.get(pk=userID)
    date = datetime.datetime.now()
    date += datetime.timedelta(minutes=1)
    targetuser.profile.block_expire = date
    targetuser.save()
    messages.success(request, 'The account has been blocked!')
    return redirect('users:user_management')

users/templates/users/change-password.html
{% extends "base.html" %}

{% block content %}
    <div class="change-password-container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="button-panel">
                <button type="submit" class="btn btn-default"> Submit form </button>
            </div>
        </form>
    </div>

{% endblock content %}

users/templates/users/edit_profile.html
{% extends "base.html" %}

{% block content %}
    <div class="edit-profile-containter">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <strong>Email address:</strong>
            </br>
            {{ user_form.email }}
            </br>
            <strong>Username:</strong>
            </br>
            {{ user_form.username }}
            </br>
            {{ profile_form.as_p }}
            </br>
            <div class="button-panel">
                <button type="submit" class="btn btn-default"> Submit form </button>
            </div>
        </form>
        </br>
        </br>
        <div class="center-block">
            <a class="btn-padding" href="{% url 'users:delete_current_account' %}" onclick="return confirm('Are you sure you want to delete your account?');">
                <div class="btn btn-danger">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                    Delete your account
                </div>
            </a>
        </div>
    </div>
    <script>
    </script>

{% endblock content %}

users/templates/users/home.html
{% extends "base.html" %}

{% block content %}

This is users home
 <p>Hello {{ user.username }}!</p>
{% endblock content %}

users/templates/users/login.html
{% extends "base.html" %}

{% block content %}

    {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
    {% endif %}
    <div class="login-container">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
                <a href="{% url 'users:reset_password' %}">Forgot password? Reset it here...</a>
            </div>
            <div class="button-panel">
               <button type="submit" class="btn btn-default">Submit</button><br>
<br>
<br>
<!-- <a href="{% url 'social:begin' 'facebook' %}" class="fa fa-facebook"></a>-->
  
  <a href="{% url 'social:begin' 'twitter' %}" class="fa fa-twitter"><span></a>
<!--  <a href="{% url 'social:begin' 'google-oauth2' %}" class="fa fa-google"><span></a>-->
  <a href="{% url 'social:begin' 'github' %}"><span><i class="fa fa-github"></i></a>
  <a href="{% url 'social:begin' backend='linkedin-oauth2' %}" class="fa fa-linkedin" ></a>
  <!--  <a href="{% url 'social:begin' backend='fouraquare' %}"></a>
  <a href="{% url 'social:begin' backend='dropbox' %}">Login with dropbox</a>
<a href="https://www.twilio.com/authorize/CN38b0f6b947f18e1ed72c8eb3f35d43ed" id="twilio-connect-button">Twilio</a>-->
  <a href="{% url 'social:begin' backend='instagram' %}"class="fa fa-instagram"></a>

</div>
        </form>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "base.html" %}

{% block content %}
    
    <h1>Succesfully logged out</h1>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block content %}

<h3>Username</h3>
<p>{{ user.username }}</p>
<h3>Email</h3>
<p>{{ user.email }}</p>
<h3>User ID</h3>
<p>{{ user.pk }}</p>


{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}

{% block content %}
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    <div class="registration-container">

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="button-panel">
                <button type="submit" class="btn btn-default"> Submit form </button>
            </div>
        </form>
    </div>
{% endblock content %}

users/templates/users/reset_password.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form> 
</div>
{% endblock %}

users/templates/users/reset_password_complete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Password reset complete</h1>
    <p>

    </p>
    <a href="{% url 'chat:home' %}">Log in</a>
</div>
{% endblock %}

users/templates/users/reset_password_confirm.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Enter the new password:</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form> 
</div>
{% endblock %}

users/templates/users/reset_password_done.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>Password reset email sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

users/templates/users/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

users/templates/users/user_management.html
{% extends "base.html" %}

{% block content %}

<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
<hr>
<div class="container bootstrap snippet">

    <!-- DELETE
    {% for user in users %}
                    <li class="list-group-item">
                        <div class="list-group-left">
                            <img src="/media/{{ user.profile.profile_photo }}" class="img-circle user-img" alt="Cinque Terre" width="304" height="236">
                            <i class="user-name" username="{{user.username}}"> {{ user.username }} </i>                          
                        </div>
                        <div class="list-group-right">
                            <a class="start-chat btn btn-sm btn-info" href="#" username="{{user.username}}" room="{{user.room}}"><i class="fa fa-commenting-o" aria-hidden="true"></i></a>
                            <a href="{% url 'users:change_friends' action='loose' pk=user.pk %}" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to remove this friend?');"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </div>
                    </li> 
                {% endfor %}
-->
{% if users %}
    <div class="row">
        <div class="col-lg-12">
            <div class="main-box no-header clearfix">
                <div class="main-box-body clearfix">
                    <div class="table-responsive">
                        <table class="table user-list">
                            <thead>
                                <tr>
                                <th><span>User</span></th>
                                <th class="text-center"><span>Status</span></th>
                                <th><span>Email</span></th>
                                <th>&nbsp;</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in users %}
                                <tr>
                                    <td>
                                        <img src="/media/{{ user.profile.profile_photo }}" alt="">
                                        <a href="#" class="user-link">{{user.username}}</a>
                                        <span class="user-subhead">ID: {{user.pk}}</span>
                                    </td>
                                    <td class="text-center">
                                        {% if user.profile.block_expire > now %}
                                            <span class="label label-warning">suspended</span>
                                            <i class="block-expire">Expires: {{ user.profile.block_expire }}</i>
                                        {% else %}
                                            <span class="label label-success">active</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a href="#">{{user.email}}</a>
                                    </td>
                                    <td style="width: 20%;">
                                        <a href="{% url 'users:block_account' userID=user.pk %}" class="table-link warning" onclick="return confirm('Are you sure you want to block this account?');">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-minus-circle fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                        <a href="{% url 'users:delete_account' userID=user.pk %}" class="table-link danger" onclick="return confirm('Are you sure you want to delete this account?');">
                                            <span class="fa-stack">
                                                <i class="fa fa-square fa-stack-2x"></i>
                                                <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %} 
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %} 
    <div class="alert alert-danger">
        <strong>There are no users in the database</strong>
    </div> 
    {% endif %}  
</div>
{% endblock content %}